// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWT4welz8sMwSli7bQY40BkxciEK0RTpY',
    appId: '1:524958440002:web:38d5922305d69392f12bdb',
    messagingSenderId: '524958440002',
    projectId: 'massmanager-ebfc8',
    authDomain: 'massmanager-ebfc8.firebaseapp.com',
    storageBucket: 'massmanager-ebfc8.firebasestorage.app',
    measurementId: 'G-PN5LCKQRYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAsIETvVQJtaGKlWcugZSNsKl4_CYsK-E',
    appId: '1:524958440002:android:faff277337403198f12bdb',
    messagingSenderId: '524958440002',
    projectId: 'massmanager-ebfc8',
    storageBucket: 'massmanager-ebfc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9-s6ea6zISa6NKzW6DFmDpL2eKhLBTKM',
    appId: '1:524958440002:ios:f4d60e48e31d1cc9f12bdb',
    messagingSenderId: '524958440002',
    projectId: 'massmanager-ebfc8',
    storageBucket: 'massmanager-ebfc8.firebasestorage.app',
    iosBundleId: 'com.example.massmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9-s6ea6zISa6NKzW6DFmDpL2eKhLBTKM',
    appId: '1:524958440002:ios:f4d60e48e31d1cc9f12bdb',
    messagingSenderId: '524958440002',
    projectId: 'massmanager-ebfc8',
    storageBucket: 'massmanager-ebfc8.firebasestorage.app',
    iosBundleId: 'com.example.massmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWT4welz8sMwSli7bQY40BkxciEK0RTpY',
    appId: '1:524958440002:web:2cfc1d44838093fef12bdb',
    messagingSenderId: '524958440002',
    projectId: 'massmanager-ebfc8',
    authDomain: 'massmanager-ebfc8.firebaseapp.com',
    storageBucket: 'massmanager-ebfc8.firebasestorage.app',
    measurementId: 'G-QLL9JW8FE9',
  );
}
